def run_cli(argv: list[str]) -> None:
    """Run the bookmarks CLI with the given arguments."""
    ...

class UrlEntry:
    """A bookmark URL entry with optional aliases."""

    def __init__(self, url: str, aliases: list[str] | None = None) -> None: ...
    @property
    def url(self) -> str: ...
    @url.setter
    def url(self, value: str) -> None: ...
    @property
    def aliases(self) -> list[str]: ...
    def add_alias(self, alias: str) -> None: ...
    def remove_alias(self, alias: str) -> None: ...
    def has_alias(self, alias: str) -> bool: ...
    def __repr__(self) -> str: ...

class Config:
    """Bookmarks configuration with URLs and groups."""

    def __init__(self) -> None: ...
    @staticmethod
    def from_toml(s: str) -> "Config": ...
    def to_toml(self) -> str: ...
    @property
    def urls(self) -> dict[str, UrlEntry]: ...
    @property
    def groups(self) -> dict[str, list[str]]: ...
    def resolve(self, name: str) -> str | None: ...
    def contains(self, name: str) -> bool: ...
    def validate(self) -> list[str]: ...
    def add_url(
        self, name: str, url: str, aliases: list[str] | None = None
    ) -> None: ...
    def rename_url(self, old: str, new: str) -> None: ...
    def rename_alias(self, old: str, new: str) -> None: ...
    def delete_url(self, name: str) -> None: ...
    def delete_alias(self, alias: str) -> None: ...
    def rename_group(self, old: str, new: str) -> None: ...
    def delete_group(self, name: str) -> None: ...
    def __repr__(self) -> str: ...

class TomlStorage:
    """TOML file-based storage backend."""

    def __init__(self, path: str) -> None: ...
    @staticmethod
    def default_path() -> str: ...
    @staticmethod
    def with_default_path() -> "TomlStorage": ...
    def load(self) -> Config: ...
    def save(self, config: Config) -> None: ...
    def init(self) -> None: ...
    def backend_name(self) -> str: ...
    def path(self) -> str | None: ...
